### ISSUE TITLE
Usage documentation from cakebuild.net is not working

### ISSUE THREAD

**Issue by escarls** [cake-contrib/Cake.Yaml#25]
The documentation from cakebuild.net (the reference section) tell me to add this to my script to use Cake.Yaml
`#addin package:?Cake.Yaml`
`#addin package:?YamlDotNet&version=4.2.1`

I tried that using Cake 1.1.0, 1.0.0, 0.38.5 and even older versions of Cake.
All of them gave me the same exception, that the Uri was wrong and were missing package=

## Expected Behavior
It should have just worked.

## Current Behavior
Running Cake will stop with an exception telling me that the addin uri is not following the correct standards.

## Possible Solution
I think it's just to change line 17 and 18 in [YamlAliases.cs](https://github.com/cake-contrib/Cake.Yaml/blob/56ab7ed47d97e6e70b89934159586220453437bc/src/Cake.Yaml/YamlAliases.cs#L17)
I am planning to make a pr to fix this, however, I really couldn't find much information on the Uri used in the current documentation, so I thought it would be good to check here first.

## Steps to Reproduce (for bugs)
1. Create a new build.cake file.
2. Add only the two lines of code from the [documentation](https://cakebuild.net/dsl/yaml/)
3. .\build.ps1 or dotnet cake to run build.cake

## Your Environment
* Addin version used: Not relevant
* Cake Version used: 1.1.0, 1.0.0, 0.38.5, 0.32.0, 0.17.0, 0.16.0
* Operating System: Windows 10

**Comment by augustoproiete** [comment]
@escarls Thanks for reporting this. Indeed the documentation in [YamlAliases.cs](https://github.com/cake-contrib/Cake.Yaml/blob/56ab7ed47d97e6e70b89934159586220453437bc/src/Cake.Yaml/YamlAliases.cs#L17-L18) is incorrect.

The syntax of the #addin preprocessor directive is

```cakescript
#addin nuget:?package=NuGetPackageName&version=x.y.z
```

Where `NuGetPackageName` is the name of the NuGet pacakge, and `x.y.z` is the version of the NuGet package to use. Thus the fix could be:

```diff
-#addin package:?Cake.Yaml
+#addin nuget:?package=Cake.Yaml&version=x.y.z

-#addin package:?YamlDotNet&version=4.2.1
+#addin nuget:?package=YamlDotNet&version=x.y.z
```

Feel free to send a PR for the above.

---

FYI, in the website we are able to generate the preprocessor directive for the addin automatically, for the latest version available. The code in the green :green_circle: arrow is generated by the website and is correct, and the code in the yellow :yellow_circle: arrow is generated from the XML docs you saw on [YamlAliases.cs](https://github.com/cake-contrib/Cake.Yaml/blob/56ab7ed47d97e6e70b89934159586220453437bc/src/Cake.Yaml/YamlAliases.cs#L17-L18).

![image](https://user-images.githubusercontent.com/177608/118535115-72ee7a00-b720-11eb-9700-ae84e93ab70f.png)
