### ISSUE TITLE
Enable Source Link in Cake.Yaml

### ISSUE THREAD

**Issue by augustoproiete** [cake-contrib/Cake.Yaml#35]
![image](https://user-images.githubusercontent.com/177608/118706968-5a4d9500-b7f0-11eb-986e-81714e9fec49.png)

**Comment by escarls** [comment]
Requires Cake.Recipe 2.0.0 or newer https://github.com/cake-contrib/Cake.Recipe/releases/tag/2.0.0.
The current build is using Cake.Recipe 1.0.0.
