### ISSUE TITLE
The unit tests are dotnetapp2.0 and that is EOL.

### ISSUE THREAD

**Issue by escarls** [cake-contrib/Cake.Yaml#37]
When building on a brand new laptop with only Visual Studio 2019 16.10.x
You will get this in the build log during testing:
A total of 1 test files matched the specified pattern.
Testhost process exited with error: It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.0.0' was not found.

## Expected Behavior
The tests should be run.

## Current Behavior
Tests fails and teardown is run.

## Possible Solution
Change the TargetFramework tag to netcoreapp3.1
Alternatively change the tag to TargetFrameworks and value to net50;netcoreapp3.1 to run the unit tests both on dotnet core 3.1 and 5.0.
I suggest to leave out 2.1 as dotnet core 2.1 is end of life in August 2021.

**Comment by escarls** [comment]
I can fix this @augustoproiete

**Comment by augustoproiete** [comment]
Awesome! Thanks @escarls. Assigning to you then
