### ISSUE TITLE
Update Cake.YML to Cake.Core version 0.22.0

### ISSUE THREAD

**Issue by mdmoura** [cake-contrib/Cake.Yaml#4]
I am having the following error when using Cake.YML with Cake lastest version:

`
Could not find assemblies compatible with .NETFramework,Version=v4.6.1 in NuGet package Cake.Git. Falling back to using root folder of NuGet package. Error: The assembly 'Cake.Yaml, Version=1.0.6333.34208, Culture=neutral, PublicKeyToken=null' is referencing an older version of Cake.Core (0.17.0). This assembly need to reference at least Cake.Core version 0.22.0.
`

When will Cake.YML be updated? Any ETA?

I have my build scripts dependent on it.

Thank You

**Comment by pascalberger** [comment]
Cake 0.22.0 support was added with [Cake.Yaml 2.0.0](https://github.com/cake-contrib/Cake.Yaml/releases/tag/2.0.0)
